### ISSUE TITLE
Github repository name vs package name?

### ISSUE THREAD

**Issue by syoh** [dddlab/robust_selection#1]
Would it cause any problems if we changed the repository name from `robust_selection` to `robust-selection`?
If that works, the new repository name would be the same as Pypi module name: `https://pypi.org/project/robust-selection/`

**Comment by cbtran** [comment]
We can change the repo name to `robust-selection`. I will update the setup file to match the new repo name.

**Comment by syoh** [comment]
Repository name has been updated
